kind: role
metadata:
  id: 1663312965131760483
  name: prod-access
spec:
  allow:
    logins:
    - '{{internal.logins}}'
    - root
    - ubuntu
    - ec2-user
    node_labels:
      'env': 'prod'
    windows_desktop_labels:
      'env': 'prod'
    windows_desktop_logins:
    - Administrator
    - svc-teleport
  deny: {}
  options:
    cert_format: standard
    create_host_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      default: best_effort
      desktop: true
    ssh_file_copy: true
version: v5
